### ISSUE TITLE
What does full 9D fix stand for?

### ISSUE THREAD

**Issue by AlexYangROS** [ros-drivers/novatel_span_driver#15]

**Comment by mikepurvis** [comment]
Position XYZ, Velocity XYZ, Acceleration XYZ, and implicitly, time.

I'm assuming you're referencing [this comment](https://github.com/ros-drivers/novatel_span_driver/issues/2#issuecomment-164765620), where the context is that the system needs to have computed this before it can supply corrected IMU-type data (vs supplying raw data directly from the IMU).

**Comment by AlexYangROS** [comment]
Thank you!   Do you mean that 9D fix no need to concern about the  Roll,Pitch,Roll and its respective velocities ? Right?
15-D state of the vehicle (x, y, z, roll, pitch, yaw, their respective velocities, and linear acceleration).

**Comment by mikepurvis** [comment]
You'd have to consult the Novatel materials for those details; I don't have a clear enough sense of how it works inside.

**Comment by AlexYangROS** [comment]
![publisher 9d fix](https://cloud.githubusercontent.com/assets/16314919/11832212/ebba281a-a3f0-11e5-9fff-4954b0b1cd78.png)

**Comment by mikepurvis** [comment]
As far as I understand it, the corrimudata message is the SPAN system providing the pieces of its solution which correspond to traditional IMU data— angular velocity from a gyroscope, and a linear acceleration vector from an accelerometer.

The 9 dimensions [reported in the comprehensive INSPVAX message](https://github.com/ros-drivers/novatel_span_driver/blob/master/novatel_msgs/msg/INSPVAX.msg#L31), though, are x,y,z, xv, yv, zv, roll, pitch, and yaw. So perhaps "9D fix" is not a very helpful thing to say when it's clearly tracking more than just 9.

**Comment by JWhitleyAStuff** [comment]
Old issue with no obvious solution - just Q&A. Closing.

**Comment by weisongwen** [comment]
Dear @JWhitleyAStuff @mikepurvis 
when I collect data from SPAN-CPT using this driver. I find that the imu data in topic  "imu/data", the linear acceleration in Z direction is just 1.02m/ss . it should be about 9.8m/ss as a result of gravity. Why can this happen?
``self.pub_imu = rospy.Publisher('imu/data', Imu, queue_size=1)``

Thanks a lot,
Best 
Welson
