### ISSUE TITLE
Bypass GNSS update?

### ISSUE THREAD

**Issue by Benjaminmar8** [ros-drivers/novatel_span_driver#17]
Is it possible to obtain /navsat/odom purely based on IMU and wheel encoder? In other words, bypass GNSS. The reason I am doing this is because our vehicle platform has to drive in indoor most of the time. Thanks a lot!

**Comment by LiShuaixin** [comment]
Hi, I have a same quetion if it can works when I try to subscribe the sensors_msgs/odom purely based on IMU?

**Comment by trainman419** [comment]
I suspect that no one who maintains this driver knows the answer to this question.

This sounds like something internal to the device, so you'll probably get a better answer if you contact Novatel's support directly.

**Comment by LiShuaixin** [comment]
I've just contact with our local dealer, he said that the IMU must be triggered by GNSS signal. It seems like a device internal problem and cannot be fixed through software

**Comment by maximus5684** [comment]
This is correct. The NovAtel devices are GPS/GNSS devices first and use the IMU and wheel encoder data to correct/augment those functions.

**Comment by JWhitleyAStuff** [comment]
(my comment from a different account above - closing issue)
