### ISSUE TITLE
Should publish IMU data whether a fix is had or not

### ISSUE THREAD

**Issue by mikepurvis** [ros-drivers/novatel_span_driver#2]

**Comment by Benjaminmar8** [comment]
Thanks for the excellent driver. Pub IMU data whether there is a fix or not seems necessary. I am trying to get this to work but no idea where to start. Any suggestion?

**Comment by mikepurvis** [comment]
Been a while since I looked at this, but my recollection is that the the [corrimudata](https://github.com/ros-drivers/novatel_span_driver/blob/35e911b8674a792803f0220b3931a4425e217f2e/novatel_span_driver/src/novatel_span_driver/publisher.py#L105) message is only sent from the underlying platform when it has its full 9D fix. There's a different message published all the time, but it's not transformed into vehicle frame, so that would then have to be handled in the driver.

**Comment by Benjaminmar8** [comment]
What is this different message you are referring? Is it one of the INS logs (page 107) in http://www.novatel.com/assets/Documents/Manuals/OM-20000144UM.pdf  thanks!

**Comment by mikepurvis** [comment]
I believe the INSXXXX logs will only output when the INS has its full solution, whereas the RAWIMUXX logs will output any time one of the supported IMUs is connected— so yes, to fix this would require using one of those messages instead (or in supplement-to, perhaps on a different topic, with a different TF frame).

**Comment by Benjaminmar8** [comment]
Thanks! Will try it out and post the solution here if successful. By the way, we are using a KVH1750 IMU.

**Comment by JWhitleyAStuff** [comment]
I'll verify with Novatel that this is the case before closing this issue.

**Comment by JWhitleyAStuff** [comment]
@Benjaminmar8 - Verified with Novatel support. Here is their reply:

"Any INSXXX log will report zeroes until the system is aligned, so after GNSS fix is obtained."

Thanks.
