### ISSUE TITLE
Euler to Quaternion conversion is incorrect.

### ISSUE THREAD

**Issue by Jebediah** [ros-drivers/novatel_span_driver#21]
In the publisher here, https://github.com/ros-drivers/novatel_span_driver/blob/master/novatel_span_driver/src/novatel_span_driver/publisher.py#L196

eulers are given to the conversion function in a pitch, roll, yaw ordering. It should be roll, pitch, yaw. (see https://github.com/ros/geometry/blob/hydro-devel/tf/src/tf/transformations.py#L1100).

Also, tacking height onto a UTM position to produce a local position may not be correct depending on the application.

**Comment by JWhitleyAStuff** [comment]
@Jebediah - #10 attempts to address this issue. I will be testing it soon. Please keep an eye on that PR. If it is not closed or is closed without resolution in the next couple of weeks, please open a new issue or PR with suggested changes. Thanks.
