### ISSUE TITLE
discarded almost all the data when using the SPAN-CPT driver 

### ISSUE THREAD

**Issue by weisongwen** [ros-drivers/novatel_span_driver#24]
Hi, when I use the driver [here](https://github.com/ros-drivers/novatel_span_driver/tree/serial_connection) .
this version is developed for SPAN-CPT with serial connection. But when I use this , I encounter problems as following:
![span-cpt](https://user-images.githubusercontent.com/24927996/29910598-15a3d556-8e5d-11e7-8442-780d1e9d1499.png)

it seems that the driver discarded almost all the data. 

Anyone could help me? Thanks a lot!

**Comment by weisongwen** [comment]
Dear all, this issue have already been tackled, the problem was the ourput content of my SPAN-CPT which was not adapted to the Driver provided here.

**Comment by JWhitleyAStuff** [comment]
Thanks for the feedback, @weisongwen. Closing this issue.

**Comment by weisongwen** [comment]
noted with thanks
