### ISSUE TITLE
Orthometric to Ellipsoidal Conversion

### ISSUE THREAD

**Issue by michaelhsmart** [ros-drivers/novatel_span_driver#26]
Hello! I believe I have discovered a bug in the altitude conversion used for [producing the NavSatFix message](https://github.com/ros-drivers/novatel_span_driver/blob/master/novatel_span_driver/src/novatel_span_driver/publisher.py#L162).

[sensor_msgs/NavSatFix](http://docs.ros.org/api/sensor_msgs/html/msg/NavSatFix.html) altitude is defined relative to the WGS 84 ellipsoid, while the [BESTPOS altitude](https://www.novatel.com/assets/Documents/Manuals/OM-20000144UM.pdf#page=123) looks like it uses height above mean sea level (geoid / orthometric height).

[This application note](https://www.novatel.com/assets/Documents/Bulletins/apn006.pdf#page=2) gives the formula for conversion using the undulation value.

I can open a pull request for the [fix](https://github.com/michaelhsmart/novatel_span_driver/tree/ellipsoidal_from_orthometric) if desired.

**Comment by mikepurvis** [comment]
Sure, that would be great! I only ever used the height in a relative way, so it didn't matter for me, but it's great to get the absolute value correct as well.

**Comment by michaelhsmart** [comment]
Will do.

We were comparing results with recordings from a third party source and the altitude values disagreed by almost exactly the undulation value. Quite the clue.
