### ISSUE TITLE
Make release for Kinetic

### ISSUE THREAD

**Issue by cglwn** [ros-drivers/novatel_span_driver#28]
Could a release be done for Kinetic? I haven't done a release myself but would be happy to assist with this if this is something the projects' maintainer is interested in.

**Comment by icolwell** [comment]
Hi @cglwn, do you mean make a compiled release to a package repo so that it can be installed via `apt`?
In our group we just clone the repo into our local catkin workspace to use it. It currently works just fine on kinetic.

**Comment by cglwn** [comment]
Yes, that would simplify things a lot for distributing dependent software. I myself also just checked it out but this adds another step to our build process which I'd like to smooth out.

**Comment by JWhitleyAStuff** [comment]
@icolwell and @cglwn - The release has been generated. It may take a day or so for the binary files to be created but they will be available in the ShadowFixed repository within a couple of days (see http://wiki.ros.org/ShadowRepository for more info). They will then be made available with the next sync from Shadow to main (usually 2-4 weeks).

**Comment by JWhitleyAStuff** [comment]
You can watch https://discourse.ros.org/tags/release for the sync date.

**Comment by icolwell** [comment]
Awesome, thanks for following up!

**Comment by cglwn** [comment]
Thanks @JWhitleyAStuff!
