### ISSUE TITLE
how to modify the frequency of imu/data topic ?

### ISSUE THREAD

**Issue by weisongwen** [ros-drivers/novatel_span_driver#29]
Hi,
The frequency of 'imu/data' is only 1hz using current novatel_span_driver when collecting data from span-cpt. how can I change this output frequency to 10hz?

Best,
Welson

**Comment by goldbattle** [comment]
You should be able to specify what you want the log frequency to be at (`<rosparam ns="configuration"></rosparam>` in the launch file). Ensure that you also change your imu rate parameters as those are used to calculate the covariance (`<param name="rate" value="100" />` in launch file).
```xml
log_request:
    bestposb: 0.05
    corrimudatab: 0.05
    inspvaxb: 0.05 #this is 100hz
    rawimuxb: 0.005 #this is 200hz
```
The default IMU data is with gravity subtracted, I you want the RAW imu data, checkout this fork:
https://github.com/rpng/novatel_span_driver

**Comment by weisongwen** [comment]
Hi, @goldbattle  
Thanks for your kind advice,
These log request should be set in windows using the software provided by novatel?
``
log_request:
    bestposb: 0.05
    corrimudatab: 0.05
    inspvaxb: 0.05 #this is 100hz
    rawimuxb: 0.005 #this is 200hz
``

**Comment by goldbattle** [comment]
You would set them in your launch file:
https://github.com/ros-drivers/novatel_span_driver/blob/master/novatel_span_driver/launch/example.launch#L8-L26
