### ISSUE TITLE
Power Argument Order

### ISSUE THREAD

**Issue by jonla1** [ros-drivers/novatel_span_driver#38]
Hi,

I am not familiar with the exact values that are stored in INSPVAX but from the naming I assume it is the standard deviation.

Therefore I think that argument order of pow in novatel_span_driver/src/novatel_span_driver/publisher.py  is wrong.

E.g.         
```
odom.pose.covariance[21] = self.orientation_covariance[0] = pow(2, inspvax.pitch_std)
odom.pose.covariance[28] = self.orientation_covariance[4] = pow(2, inspvax.roll_std)
odom.pose.covariance[35] = self.orientation_covariance[8] = pow(2, inspvax.azimuth_std)
```
should be in fact 
```
odom.pose.covariance[21] = self.orientation_covariance[0] = pow(inspvax.pitch_std,2)
odom.pose.covariance[28] = self.orientation_covariance[4] = pow(inspvax.roll_std,2)
odom.pose.covariance[35] = self.orientation_covariance[8] = pow(inspvax.azimuth_std,2)
```
since the covariance is the squared standard deviation.

This also applies to line 163-165, 202-204, 210-212

Could someone confirm this in fact correct?

**Comment by JWhitleyAStuff** [comment]
@jonla1 - This looks correct from the documentation for std::pow() and you are correct in assuming that these are the standard deviation values - INSPVAX was, in fact, replaced by INSSTDDEV in the OEM7 firmware (for the PwrPak7). Would you mind submitting a Pull Request to correct this issue?

**Comment by jonla1** [comment]
According to [Novatel](https://docs.novatel.com/OEM7/Content/Integration_Guide_OEM6_OEM7/Logs_OEM6_to_OEM7.htm?TocPath=New%20for%20OEM7%7COEM6%20to%20OEM7%20Integration%7C_____2) INSSTDDEV only replaces INSCOV.

**Comment by JWhitleyAStuff** [comment]
@jonla1 - Sorry, you are correct. The standard deviation data is included in the INSPVAX message and the direct replacement was from INSCOV to INSSTDDEV. However, if you look at the OEM7 data for INSPVAX, it recommends logging INSSTDDEV (https://docs.novatel.com/OEM7/Content/SPAN_Logs/INSPVAX.htm) and the OEM6 manual recommends INSCOV (https://www.novatel.com/assets/documents/manuals/om-20000144um.pdf, page 148). Your assumption about the meaning of these values is correct.
