### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by J-pcy** [ros-drivers/novatel_span_driver#41]
2 questions about driver and configuration. First, do you have any driver based on C++. Second, I got many user manual and configuration file based on win7. Do I need to do any other preparation if I use this ros driver to connect my PwrPak7?

**Comment by JWhitleyAStuff** [comment]
There is another driver based on C++ - it's the [novatel_gps_driver](https://github.com/swri-robotics/novatel_gps_driver). The feature set is not identical between the two (e.g. some messages are supported on one but not the other and the C++ driver does not currently support passing through wheel encoder data) but it is very stable and works for the ProPak6 and PwrPak7. Both drivers connect over Ethernet and configure the device upon connect so you shouldn't need any additional configuration. The SwRI driver can also connect via serial.
