### ISSUE TITLE
How to get RTK data to SPAN device

### ISSUE THREAD

**Issue by mikepurvis** [ros-drivers/novatel_span_driver#5]
Should this be a separate node? Part of the main driver? A standalone thing?

In any case, this must be figured and either implemented or at least documented.

**Comment by martinmagnusson** [comment]
Is this still an issue? Is it not possible to use novatel_span_driver with a RTK-GPS subscription?

**Comment by icolwell** [comment]
The novatel_span_driver will use whatever data gets sent via the novatel logs. It is up to the user to configure the span device to listen to RTK data on a certain interface. So yes, the novatel_span_driver can be used while the span device is receiving RTK corrections.

I believe this topic was raised to address how to pass correction data from the ROS environment into the SPAN device using the novatel_span_driver. Although I may be wrong.

**Comment by JWhitleyAStuff** [comment]
This is very much a function of the receiver itself. RTK data has to be incorporated at the receiver level and is used to generate the provided solution. The receiver can use either an internet-based NTRIP Caster or a local radio receiver (something like DSRC) to talk to a base station directly. Either way, these are handled by the receiver (either through it's built-in NTRIP Client or a serial port).
