### ISSUE TITLE
Euler to quaterion conversion of INSPVA

### ISSUE THREAD

**Issue by prclibo** [ros-drivers/novatel_span_driver#6]
Hello,

Thanks for contributing this driver to the ROS community. We are planning to use this driver and I would like to inquiry about the rotation conversion of INSPVA in this driver.

In [this line](https://github.com/ros-drivers/novatel_span_driver/blob/master/novatel_span_driver/src/novatel_span_driver/publisher.py#L196):

    self.orientation = tf.transformations.quaternion_from_euler(
        radians(inspvax.pitch),
        radians(inspvax.roll),
        radians(90 - inspvax.azimuth))

The orientation is formed in the order of rotating around x, around y and around z (i.e. xyz order). However, in the [_Application Note on Vehicle to Body Rotations_](http://www.novatel.com/assets/Documents/Bulletins/apn037.pdf), I noticed that rotation is denoted by yxz or zxy order. This confuses us. Could you please explain if the code is consistent with documents? Thank you!

**Comment by mikepurvis** [comment]
Hi! Sorry for the late response.

I agree that that looks out of agreement with the NovAtel documentation. I no longer recall the circumstances which led to it being the way it is, but it was likely just empirical— tilting the device on my desk, observing the orientation in rviz, and adjusting the output accordingly.

I would welcome a PR which adds a clarifying comment, or even modifies it, if you find a way which makes more sense.
